# frozen_string_literal: true
require 'redis'
require 'set'
require 'timeout'
require 'wikipedia'
require './lib/wiki_game/api'
require './lib/wiki_game/engine'
require './lib/wiki_game/algorithms/graph_search'
require './lib/wiki_game/algorithms/breadth_first_search'
require './lib/wiki_game/algorithms/depth_first_search'
require './lib/wiki_game/analyzers/elasticsearch_analyzer'
