# frozen_string_literal: true
require 'wikipedia'
require 'set'
require 'timeout'
require './lib/wiki_game/api'
require './lib/wiki_game/engine'
require './lib/wiki_game/algorithms/graph_search'
require './lib/wiki_game/algorithms/breadth_first_search'
require './lib/wiki_game/algorithms/breadth_first_search_page_rank'
require './lib/wiki_game/algorithms/depth_first_search'
require './lib/wiki_game/data_analyzers/elasticsearch_analyzer.rb'
